CREATE TABLE F23_S003_T5_CUSTOMER (
   CustomerID VARCHAR(10) NOT NULL,
   Fname VARCHAR(20) NOT NULL,
   Lname VARCHAR(20) NOT NULL,
   Gender CHAR(10) NOT NULL, 
   DOB DATE NOT NULL,
   Occupation VARCHAR(50) NOT NULL, 
   start_date DATE NOT NULL, 
   PRIMARY KEY (CustomerID)
);

CREATE TABLE F23_S003_T5_CUSTOMER_ADDRESS (
   CustomerID VARCHAR(10) NOT NULL,
   Country VARCHAR(100) NOT NULL, 
   ZIPCode VARCHAR(20) NOT NULL,
   City VARCHAR(50) NOT NULL, 
   PRIMARY KEY (CustomerID),
   FOREIGN KEY (CustomerID) REFERENCES F23_S003_T5_CUSTOMER(CustomerID) 
);

CREATE TABLE F23_S003_T5_MEMBER (
   CustomerID VARCHAR(10) NOT NULL,
   USER_NAME VARCHAR(20) NOT NULL,
   primary key(CustomerID)
	);

CREATE TABLE F23_S003_T5_NON_MEMBER (
   CustomerID VARCHAR(10) NOT NULL,
   TEMP_USER_NAME VARCHAR(20) NOT NULL,
primary key(CustomerID)  
	);

CREATE TABLE F23_S003_T5_BOOKS (
   BOOKID VARCHAR(10) NOT NULL,
   BOOK_NAME VARCHAR(200) NOT NULL,
   PRICE DECIMAL(10,2) NOT NULL,
   GENRE VARCHAR(20) NOT NULL,
   CUSTOMER_RATING VARCHAR (10) NOT NULL,
   PRIMARY KEY (BOOKID)
	);

CREATE TABLE F23_S003_T5_BOOK_LANGUAGE (
   BOOKID VARCHAR(10) NOT NULL,
   LANGUAGE VARCHAR (20) NOT NULL,
   PRIMARY KEY(BOOKID),
   FOREIGN KEY (BOOKID) REFERENCES F23_S003_T5_BOOKS(BOOKID)
	);

CREATE TABLE F23_S003_T5_BOOKS_PUBLISHED_BY (
   BOOKID VARCHAR(10) NOT NULL,
   PUBLISHERID VARCHAR(10) NOT NULL,
   DATE_OF_PUBLICATION DATE NOT NULL,
   COUNT_OF_PUBLISHED_BOOKS INT NOT NULL,
   PRIMARY KEY(BOOKID),
   FOREIGN KEY (BOOKID) REFERENCES F23_S003_T5_BOOKS(BOOKID) 
	);

--Authors:
CREATE TABLE F23_S003_T5_AUTHORS (
   AUTHORID VARCHAR(10) NOT NULL,
   AUTHOR_NAME VARCHAR(200) NOT NULL,
   GENDER CHAR(10) NOT NULL,
   ETHNICITY VARCHAR(50),
   COUNTRY VARCHAR (50),
   DOB DATE NOT NULL,
    PRIMARY KEY (AUTHORID)
	);

--Author writes:

CREATE TABLE F23_S003_T5_WRITES (
   BOOKID VARCHAR(10) NOT NULL,
   AUTHORID VARCHAR(10) NOT NULL,
   PRIMARY KEY (AUTHORID, BOOKID),
   FOREIGN KEY (AUTHORID) REFERENCES F23_S003_T5_AUTHORS(AUTHORID),
   FOREIGN KEY (BOOKID) REFERENCES F23_S003_T5_BOOKS(BOOKID)
	);

--Publishers:

CREATE TABLE F23_S003_T5_PUBLISHER (
   PUBLISHERID VARCHAR(10) NOT NULL,
   PUBLISHER_NAME VARCHAR(50),
   LOCATION VARCHAR(20) NOT NULL,
   PRIMARY KEY (PUBLISHERID)
	);

CREATE TABLE F23_S003_T5_PUBLISHER_LANGUAGE (
   PUBLISHERID VARCHAR(10) NOT NULL,
   LANGUAGE VARCHAR(20) NOT NULL,
   PRIMARY KEY (PUBLISHERID),
   FOREIGN KEY (PUBLISHERID) REFERENCES F23_S003_T5_PUBLISHER(PUBLISHERID)
	);

CREATE TABLE F23_S003_T5_PUBLISHER_GENRES (
   PUBLISHERID VARCHAR(10) NOT NULL,
   GENRE VARCHAR(100) NOT NULL,
   PRIMARY KEY (PUBLISHERID),
   FOREIGN KEY (PUBLISHERID) REFERENCES F23_S003_T5_PUBLISHER(PUBLISHERID)
	);

CREATE TABLE F23_S003_T5_PUBLISHED_BY (
   PUBLISHERID VARCHAR(10) NOT NULL,
   AUTHORID VARCHAR(10) NOT NULL,
   PRIMARY KEY (PUBLISHERID, AUTHORID),
   FOREIGN KEY (AUTHORID) REFERENCES F23_S003_T5_AUTHORS(AUTHORID),
   FOREIGN KEY (PUBLISHERID) REFERENCES F23_S003_T5_PUBLISHER(PUBLISHERID)
	);


--Member reads:

CREATE TABLE F23_S003_T5_READS (
   CUSTOMERID VARCHAR(10) NOT NULL,
   BOOKID VARCHAR(10) NOT NULL,
   PRIMARY KEY (CUSTOMERID, BOOKID),
   FOREIGN KEY (CUSTOMERID) REFERENCES F23_S003_T5_MEMBER(CUSTOMERID),
   FOREIGN KEY (BOOKID) REFERENCES F23_S003_T5_BOOKS(BOOKID)
	);

--Member reads:

CREATE TABLE F23_S003_T5_HAS_LIMITED_ACCESS (
   CUSTOMERID VARCHAR(10) NOT NULL,
   BOOKID VARCHAR(10) NOT NULL,
   PRIMARY KEY (CUSTOMERID, BOOKID),
   FOREIGN KEY (CUSTOMERID) REFERENCES F23_S003_T5_NON_MEMBER(CUSTOMERID),
   FOREIGN KEY (BOOKID) REFERENCES F23_S003_T5_BOOKS(BOOKID)
	);


